# Generated by Django 4.2.8 on 2024-05-23 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarberia', '0010_barberia_insta_barberia_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
