# Generated by Django 4.2.8 on 2024-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarberia', '0011_cita_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='plan',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Deluxe', 'Deluxe'), ('VIP', 'VIP')], default='Básico', max_length=10),
        ),
    ]
